In [1]:
import torch

This file contains the practice questons for the module 00_code.ipynv file.

In [2]:
# 2. Create a random tensor with shape (7, 7).
tensor1 = torch.rand(7,7)
tensor1

tensor([[0.7775, 0.0707, 0.9594, 0.8068, 0.4378, 0.0387, 0.0612],
        [0.1888, 0.8856, 0.5352, 0.2416, 0.1383, 0.8527, 0.6977],
        [0.4292, 0.8430, 0.5780, 0.5483, 0.1656, 0.8948, 0.0287],
        [0.5705, 0.6106, 0.3098, 0.9970, 0.4590, 0.0592, 0.1453],
        [0.7869, 0.1370, 0.7497, 0.2609, 0.5289, 0.1125, 0.1297],
        [0.3974, 0.4926, 0.6531, 0.4016, 0.7262, 0.4134, 0.0441],
        [0.7529, 0.7117, 0.3293, 0.7276, 0.5436, 0.6811, 0.0355]])

In [3]:
# 3. Perform a matrix multiplication on the tensor1 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

tensor2 = torch.rand(1,7)
tensor2_transpose = tensor2.T

mat_mul_result = torch.matmul(tensor1, tensor2_transpose)
mat_mul_result

tensor([[2.1478],
        [2.2225],
        [2.5062],
        [1.7527],
        [1.8389],
        [1.8881],
        [2.4271]])

In [6]:
# 4. Set the random seed to 0 and do exercises 2 & 3 over again
torch.manual_seed(0)
tensor1 = torch.rand(7,7)

torch.manual_seed(0)
tensor2 = torch.rand(1,7)

tensor2_transpose = tensor2.T

mat_mul_result = torch.matmul(tensor1, tensor2_transpose)
mat_mul_result

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [7]:
# 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
torch.cuda.manual_seed(1234)

In [15]:
# 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
torch.cuda.manual_seed(1234)
tensor3 = torch.rand(2,3).to("cuda")
torch.cuda.manual_seed(1234)
tensor4 = torch.rand(2,3).to("cuda")

In [16]:
# 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors)
mat_mul_result2 = torch.matmul(tensor3, tensor4.T)
mat_mul_result2

tensor([[0.8576, 0.2788],
        [1.1655, 0.5516]], device='cuda:0')

In [19]:
# 8. Find the maximum and minimum values of the output of 7.
max = torch.max(mat_mul_result2)
min = torch.min(mat_mul_result2)
max, min

(tensor(1.1655, device='cuda:0'), tensor(0.2788, device='cuda:0'))

In [25]:
# 9. Find the maximum and minimum index values of the output of 7.
max_index = torch.argmax(mat_mul_result2)
min_index = torch.argmin(mat_mul_result2)
max_index, min_index

(tensor(2, device='cuda:0'), tensor(1, device='cuda:0'))

In [30]:
# 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
torch.manual_seed(7)
tensor5 = torch.rand(1,1,1,10)
print("tensor5:",tensor5)
print("Tensor5 shape:", tensor5.shape)

tensor6 = tensor5.squeeze()
print("tensor6:",tensor6)
print("Tensor6 shape:", tensor6.shape)

tensor5: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Tensor5 shape: torch.Size([1, 1, 1, 10])
tensor6: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Tensor6 shape: torch.Size([10])
