In [1]:
import torch
print(torch.__version__)

2.1.2+cu118


## Tensors
Various dimensions of tensors using pytorch

In [2]:
# Scalar
scalar = torch.tensor(4)
scalar

tensor(4)

In [3]:
print("dimensions:", scalar.ndim)
print("size:", scalar.shape)
print("Value:", scalar.item())


dimensions: 0
size: torch.Size([])
Value: 4


In [4]:
#vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [5]:
print("dimensions:", vector.ndim)
print("size:", vector.shape)
print("Value:", vector[0])

dimensions: 1
size: torch.Size([2])
Value: tensor(1)


In [19]:
#Matrix
matrix = torch.tensor([[1,2],[3,4],[5,6]], dtype=torch.float32)
matrix

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [7]:
print("dimensions:", matrix.ndim)
print("size:", matrix.shape)
print("Value:", matrix[1])

dimensions: 2
size: torch.Size([3, 2])
Value: tensor([3, 4])


In [8]:
#3d matrix
matrix_3d = torch.tensor([[[1,2],[2,3],[3,4]],[[4,5],[5,6],[6,7]],[[4,5],[5,6],[6,7]],[[4,5],[5,6],[6,7]]])
matrix_3d

tensor([[[1, 2],
         [2, 3],
         [3, 4]],

        [[4, 5],
         [5, 6],
         [6, 7]],

        [[4, 5],
         [5, 6],
         [6, 7]],

        [[4, 5],
         [5, 6],
         [6, 7]]])

In [9]:
print("dimensions:", matrix_3d.ndim)
print("size:", matrix_3d.shape)
print("Value:", matrix_3d[1])

dimensions: 3
size: torch.Size([4, 3, 2])
Value: tensor([[4, 5],
        [5, 6],
        [6, 7]])


# Random Tensors

In [10]:
random_tensor = torch.rand(2,4,3,3,3)
random_tensor

tensor([[[[[0.7031, 0.3678, 0.1457],
           [0.9517, 0.1259, 0.1184],
           [0.7703, 0.3460, 0.2637]],

          [[0.7249, 0.9351, 0.1352],
           [0.3810, 0.6459, 0.4830],
           [0.2327, 0.8175, 0.6152]],

          [[0.6321, 0.7495, 0.4899],
           [0.2576, 0.2888, 0.6540],
           [0.7677, 0.3715, 0.6879]]],


         [[[0.3673, 0.8478, 0.6258],
           [0.9504, 0.8126, 0.9787],
           [0.5003, 0.0038, 0.0280]],

          [[0.8919, 0.6794, 0.3133],
           [0.4246, 0.1720, 0.6093],
           [0.2868, 0.8054, 0.8184]],

          [[0.9515, 0.4712, 0.5063],
           [0.4860, 0.1097, 0.0506],
           [0.4144, 0.5345, 0.0579]]],


         [[[0.0259, 0.0195, 0.4746],
           [0.7485, 0.3043, 0.7118],
           [0.1291, 0.7527, 0.7530]],

          [[0.0727, 0.3190, 0.3488],
           [0.0500, 0.8167, 0.2867],
           [0.5718, 0.7848, 0.8408]],

          [[0.7476, 0.7982, 0.9678],
           [0.7006, 0.6294, 0.0014],
           [0.7373

In [11]:
print("dimensions:", random_tensor.ndim)
print("size:", random_tensor.shape)
print("Value:", random_tensor[1])

dimensions: 5
size: torch.Size([2, 4, 3, 3, 3])
Value: tensor([[[[0.4846, 0.0522, 0.5860],
          [0.2412, 0.4366, 0.7085],
          [0.1393, 0.7627, 0.9271]],

         [[0.8482, 0.8546, 0.5981],
          [0.7507, 0.5468, 0.5700],
          [0.5514, 0.1847, 0.6294]],

         [[0.8312, 0.6758, 0.0392],
          [0.5401, 0.7334, 0.2914],
          [0.5910, 0.8479, 0.8236]]],


        [[[0.9757, 0.7142, 0.5136],
          [0.8280, 0.3981, 0.4339],
          [0.0435, 0.4692, 0.8956]],

         [[0.8677, 0.8008, 0.6188],
          [0.5308, 0.5901, 0.7254],
          [0.7546, 0.6644, 0.4572]],

         [[0.3504, 0.8558, 0.1813],
          [0.1058, 0.4085, 0.4371],
          [0.4105, 0.8200, 0.9918]]],


        [[[0.9183, 0.8478, 0.5194],
          [0.8817, 0.3796, 0.3792],
          [0.5760, 0.3184, 0.7616]],

         [[0.1078, 0.5675, 0.3860],
          [0.4615, 0.9256, 0.3425],
          [0.9196, 0.7382, 0.5199]],

         [[0.7200, 0.6555, 0.6838],
          [0.8284, 0.0808

Tensor of Zeroes and Ones

In [12]:
zeros = torch.zeros(3,5,4)
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
ones  =torch.ones(2,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

Creating a range of tensors and tensors like

In [14]:
range = torch.arange(0,10)
# or
# range = torch.arange(start=0, end=10, step=1)
range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
print("dimensions:", range.ndim)
print("size:", range.shape)
print("Value:", range[1])

dimensions: 1
size: torch.Size([10])
Value: tensor(1)


In [16]:
ten_zeros = torch.zeros_like(input = range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes

In [17]:
# By default, the dtype in a tensor is float32. But we can change it to our desired type
tensor_data_ex1 = torch.tensor([1.0,2.0,3.0], dtype=None)
tensor_data_ex1.dtype

torch.float32

In [18]:
tensor_data_ex2 = torch.tensor([1.0,2.0,3.0], dtype=torch.float16)
tensor_data_ex2.dtype

torch.float16

Other Parameters in defining a tensor

In [19]:
tensor_data_ex2 = torch.tensor([1.0,2.0,3.0], 
                               dtype=torch.float32, 
                               device = "cpu", # This tells us which device the tensor resides on. It can be on cuda, cpu etc.
                               requires_grad=False # This tells us whether we should track the gradients of the tensor or not. 
                               )
tensor_data_ex2.dtype

torch.float32

# Important Point
Two tensors can only interact together when they are on the same device. For example, if a tensor t1 is on "cpu", and tensor t2 is on "cuda", then any operation between t1 and t2 will throw an error. To do the operation, t1 and t2 must be on the same device (both on cpu or cuda)

In [20]:
pro = tensor_data_ex1 * tensor_data_ex2 #Performing a tensor operation of multiplication (elementwise)
print("datatype:",pro.dtype)
print("shape:",pro.shape)
print("dimensions:",pro.ndim)
print("device:",pro.device)


datatype: torch.float32
shape: torch.Size([3])
dimensions: 1
device: cpu


Tensor Operations

In [11]:
# Some common operations on tensors are addition, subtraction , multiplication, division, matrix multiplication
op_tensor = torch.tensor([1,2,3,4])
op_tensor_2 = torch.tensor([2,3,4,5])
print("tensor+tensor:",op_tensor+op_tensor)
print("tensor-tensor:",op_tensor-op_tensor)
print("tensor*tensor:",op_tensor*op_tensor)
print("tensor/tensor:",op_tensor/op_tensor)
print("tensor+tensor:",torch.add(op_tensor, op_tensor))
print("tensor-tensor:",torch.sub(op_tensor, op_tensor))
print("tensor*tensor:",torch.mul(op_tensor, op_tensor))
print("tensor/tensor:",torch.div(op_tensor, op_tensor))
print("tensor+tensor:",torch.add(op_tensor, 10))

tensor+tensor: tensor([2, 4, 6, 8])
tensor-tensor: tensor([0, 0, 0, 0])
tensor*tensor: tensor([ 1,  4,  9, 16])
tensor/tensor: tensor([1., 1., 1., 1.])
tensor+tensor: tensor([2, 4, 6, 8])
tensor-tensor: tensor([0, 0, 0, 0])
tensor*tensor: tensor([ 1,  4,  9, 16])
tensor/tensor: tensor([1., 1., 1., 1.])
tensor+tensor: tensor([11, 12, 13, 14])


# Matrix Multiplication

In [22]:
mat_mul_ans = torch.matmul(op_tensor,torch.transpose(op_tensor,0,0))
print("Matrix multipliction:", mat_mul_ans)
print("Matrix multipliction:", len(op_tensor))

Matrix multipliction: tensor(30)
Matrix multipliction: 4


In [3]:
%%time
val=0
for i in range (4):
    val += op_tensor[i] * op_tensor[i]

print(val)

tensor(30)
CPU times: total: 0 ns
Wall time: 2.52 ms


In [20]:
%%time
matrix2 = torch.rand(2,3)
print(matrix2.dtype)
pro1 = torch.matmul(op_tensor, op_tensor) #torch's matrix multiplication method (see that it is faster than our loop implementation)
pro2 = op_tensor @ op_tensor # Another way to write matrix multiplication operation
pro3 = torch.mm(matrix, matrix2) # Another way to write matrix multiplication operation
print("Pro1:", pro1)
print("Pro2:", pro2)
print("Pro3:", pro3)

torch.float32
Pro1: tensor(30)
Pro2: tensor(30)
Pro3: tensor([[1.7540, 1.3676, 1.1536],
        [3.6681, 3.0129, 3.0447],
        [5.5821, 4.6582, 4.9359]])
CPU times: total: 0 ns
Wall time: 38.6 ms


# Transpose

In [23]:
tensor_1 = torch.tensor([[1,2],[3,4],[5,6]])
print("Shape of tensor 1:", tensor_1.shape)
tensor_2 = tensor_1.T  #Used to find the transpose of a tensor
print("Shape of tensor 2:", tensor_2.shape)


Shape of tensor 1: torch.Size([3, 2])
Shape of tensor 2: torch.Size([2, 3])
