In [1]:
import torch
print(torch.__version__)

2.1.2+cu118


## Tensors
Various dimensions of tensors using pytorch

In [2]:
# Scalar
scalar = torch.tensor(4)
scalar

tensor(4)

In [3]:
print("dimensions:", scalar.ndim)
print("size:", scalar.shape)
print("Value:", scalar.item())


dimensions: 0
size: torch.Size([])
Value: 4


In [4]:
#vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [5]:
print("dimensions:", vector.ndim)
print("size:", vector.shape)
print("Value:", vector[0])

dimensions: 1
size: torch.Size([2])
Value: tensor(1)


In [6]:
#Matrix
matrix = torch.tensor([[1,2],[3,4],[5,6]])
matrix

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [7]:
print("dimensions:", matrix.ndim)
print("size:", matrix.shape)
print("Value:", matrix[1])

dimensions: 2
size: torch.Size([3, 2])
Value: tensor([3, 4])


In [8]:
#3d matrix
matrix_3d = torch.tensor([[[1,2],[2,3],[3,4]],[[4,5],[5,6],[6,7]],[[4,5],[5,6],[6,7]],[[4,5],[5,6],[6,7]]])
matrix_3d

tensor([[[1, 2],
         [2, 3],
         [3, 4]],

        [[4, 5],
         [5, 6],
         [6, 7]],

        [[4, 5],
         [5, 6],
         [6, 7]],

        [[4, 5],
         [5, 6],
         [6, 7]]])

In [9]:
print("dimensions:", matrix_3d.ndim)
print("size:", matrix_3d.shape)
print("Value:", matrix_3d[1])

dimensions: 3
size: torch.Size([4, 3, 2])
Value: tensor([[4, 5],
        [5, 6],
        [6, 7]])


# Random Tensors

In [12]:
random_tensor = torch.rand(4,3,3,3)
random_tensor

tensor([[[[0.9197, 0.6925, 0.3928],
          [0.2429, 0.1494, 0.1132],
          [0.0295, 0.1503, 0.5560]],

         [[0.3368, 0.1359, 0.7082],
          [0.4034, 0.6833, 0.4847],
          [0.8790, 0.9520, 0.6641]],

         [[0.1490, 0.4952, 0.4489],
          [0.2535, 0.1847, 0.1700],
          [0.2119, 0.7212, 0.3021]]],


        [[[0.2734, 0.5570, 0.7667],
          [0.8384, 0.6693, 0.3344],
          [0.4358, 0.1174, 0.9223]],

         [[0.4954, 0.8565, 0.0323],
          [0.0863, 0.8493, 0.0386],
          [0.9414, 0.5428, 0.6765]],

         [[0.2463, 0.8940, 0.8557],
          [0.5734, 0.8148, 0.7181],
          [0.9427, 0.5196, 0.6522]]],


        [[[0.6460, 0.3417, 0.2542],
          [0.7579, 0.1176, 0.0141],
          [0.6947, 0.1924, 0.5316]],

         [[0.1427, 0.2675, 0.9704],
          [0.7334, 0.3873, 0.5585],
          [0.2653, 0.7110, 0.3791]],

         [[0.4232, 0.2012, 0.9715],
          [0.1474, 0.4884, 0.4639],
          [0.2505, 0.8988, 0.0242]]],


    

In [13]:
print("dimensions:", random_tensor.ndim)
print("size:", random_tensor.shape)
print("Value:", random_tensor[1])

dimensions: 4
size: torch.Size([4, 3, 3, 3])
Value: tensor([[[0.2734, 0.5570, 0.7667],
         [0.8384, 0.6693, 0.3344],
         [0.4358, 0.1174, 0.9223]],

        [[0.4954, 0.8565, 0.0323],
         [0.0863, 0.8493, 0.0386],
         [0.9414, 0.5428, 0.6765]],

        [[0.2463, 0.8940, 0.8557],
         [0.5734, 0.8148, 0.7181],
         [0.9427, 0.5196, 0.6522]]])
