In [1]:
import torch

This file contains the practice questons for the module 00_code.ipynv file.

In [2]:
# 2. Create a random tensor with shape (7, 7).
tensor1 = torch.rand(7,7)
tensor1

tensor([[0.7775, 0.0707, 0.9594, 0.8068, 0.4378, 0.0387, 0.0612],
        [0.1888, 0.8856, 0.5352, 0.2416, 0.1383, 0.8527, 0.6977],
        [0.4292, 0.8430, 0.5780, 0.5483, 0.1656, 0.8948, 0.0287],
        [0.5705, 0.6106, 0.3098, 0.9970, 0.4590, 0.0592, 0.1453],
        [0.7869, 0.1370, 0.7497, 0.2609, 0.5289, 0.1125, 0.1297],
        [0.3974, 0.4926, 0.6531, 0.4016, 0.7262, 0.4134, 0.0441],
        [0.7529, 0.7117, 0.3293, 0.7276, 0.5436, 0.6811, 0.0355]])

In [3]:
# 3. Perform a matrix multiplication on the tensor1 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

tensor2 = torch.rand(1,7)
tensor2_transpose = tensor2.T

mat_mul_result = torch.matmul(tensor1, tensor2_transpose)
mat_mul_result

tensor([[2.1478],
        [2.2225],
        [2.5062],
        [1.7527],
        [1.8389],
        [1.8881],
        [2.4271]])

In [6]:
# 4. Set the random seed to 0 and do exercises 2 & 3 over again
torch.manual_seed(0)
tensor1 = torch.rand(7,7)

torch.manual_seed(0)
tensor2 = torch.rand(1,7)

tensor2_transpose = tensor2.T

mat_mul_result = torch.matmul(tensor1, tensor2_transpose)
mat_mul_result

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])