In [1]:
import torch
print(torch.__version__)

2.1.2+cu118


## Tensors
Various dimensions of tensors using pytorch

In [2]:
# Scalar
scalar = torch.tensor(4)
scalar

tensor(4)

In [3]:
print("dimensions:", scalar.ndim)
print("size:", scalar.shape)
print("Value:", scalar.item())


dimensions: 0
size: torch.Size([])
Value: 4


In [4]:
#vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [5]:
print("dimensions:", vector.ndim)
print("size:", vector.shape)
print("Value:", vector[0])

dimensions: 1
size: torch.Size([2])
Value: tensor(1)


In [6]:
#Matrix
matrix = torch.tensor([[1,2],[3,4],[5,6]])
matrix

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [7]:
print("dimensions:", matrix.ndim)
print("size:", matrix.shape)
print("Value:", matrix[1])

dimensions: 2
size: torch.Size([3, 2])
Value: tensor([3, 4])


In [8]:
#3d matrix
matrix_3d = torch.tensor([[[1,2],[2,3],[3,4]],[[4,5],[5,6],[6,7]],[[4,5],[5,6],[6,7]],[[4,5],[5,6],[6,7]]])
matrix_3d

tensor([[[1, 2],
         [2, 3],
         [3, 4]],

        [[4, 5],
         [5, 6],
         [6, 7]],

        [[4, 5],
         [5, 6],
         [6, 7]],

        [[4, 5],
         [5, 6],
         [6, 7]]])

In [9]:
print("dimensions:", matrix_3d.ndim)
print("size:", matrix_3d.shape)
print("Value:", matrix_3d[1])

dimensions: 3
size: torch.Size([4, 3, 2])
Value: tensor([[4, 5],
        [5, 6],
        [6, 7]])


# Random Tensors

In [10]:
random_tensor = torch.rand(2,4,3,3,3)
random_tensor

tensor([[[[[0.0304, 0.6392, 0.9320],
           [0.5627, 0.3004, 0.6007],
           [0.6612, 0.1096, 0.5203]],

          [[0.9804, 0.5527, 0.8079],
           [0.0242, 0.7030, 0.7440],
           [0.6069, 0.1468, 0.0438]],

          [[0.6688, 0.1808, 0.3541],
           [0.6918, 0.0479, 0.1344],
           [0.5531, 0.6569, 0.4720]]],


         [[[0.8123, 0.2311, 0.4813],
           [0.5907, 0.1698, 0.1441],
           [0.0846, 0.5121, 0.8896]],

          [[0.0775, 0.9105, 0.3827],
           [0.0320, 0.8484, 0.8519],
           [0.9273, 0.2907, 0.7525]],

          [[0.4426, 0.3423, 0.0010],
           [0.4489, 0.4877, 0.0644],
           [0.9410, 0.7878, 0.8435]]],


         [[[0.6669, 0.4136, 0.9881],
           [0.4863, 0.9771, 0.6988],
           [0.5274, 0.7073, 0.1454]],

          [[0.4532, 0.0832, 0.1321],
           [0.0571, 0.2494, 0.4545],
           [0.1854, 0.2717, 0.7344]],

          [[0.2683, 0.0146, 0.2026],
           [0.2443, 0.1349, 0.9450],
           [0.2224

In [11]:
print("dimensions:", random_tensor.ndim)
print("size:", random_tensor.shape)
print("Value:", random_tensor[1])

dimensions: 5
size: torch.Size([2, 4, 3, 3, 3])
Value: tensor([[[[0.5103, 0.0113, 0.0283],
          [0.0100, 0.6352, 0.9486],
          [0.1621, 0.3920, 0.1752]],

         [[0.4395, 0.7256, 0.5375],
          [0.3234, 0.6804, 0.2107],
          [0.7527, 0.6230, 0.1697]],

         [[0.7171, 0.7470, 0.6476],
          [0.5660, 0.6864, 0.7703],
          [0.0280, 0.9025, 0.8790]]],


        [[[0.1944, 0.0756, 0.2815],
          [0.2056, 0.5871, 0.4734],
          [0.1266, 0.7441, 0.3180]],

         [[0.1110, 0.7576, 0.3049],
          [0.4058, 0.3038, 0.8270],
          [0.8862, 0.4666, 0.2090]],

         [[0.6467, 0.2805, 0.1106],
          [0.4180, 0.0685, 0.2795],
          [0.7022, 0.4277, 0.5753]]],


        [[[0.0088, 0.8407, 0.5134],
          [0.3675, 0.1967, 0.2587],
          [0.1009, 0.3838, 0.9531]],

         [[0.2213, 0.6132, 0.3123],
          [0.6092, 0.1371, 0.4856],
          [0.7171, 0.9363, 0.1190]],

         [[0.8263, 0.8244, 0.4226],
          [0.7628, 0.6338

Tensor of Zeroes and Ones

In [12]:
zeros = torch.zeros(3,5,4)
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
ones  =torch.ones(2,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

Creating a range of tensors and tensors like

In [16]:
range = torch.arange(0,10)
# or
# range = torch.arange(start=0, end=10, step=1)
range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
print("dimensions:", range.ndim)
print("size:", range.shape)
print("Value:", range[1])

dimensions: 1
size: torch.Size([10])
Value: tensor(1)


In [23]:
ten_zeros = torch.zeros_like(input = range)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes

In [26]:
# By default, the dtype in a tensor is float32. But we can change it to our desired type
tensor_data_ex1 = torch.tensor([1.0,2.0,3.0], dtype=None)
tensor_data_ex1.dtype

torch.float32

In [27]:
tensor_data_ex2 = torch.tensor([1.0,2.0,3.0], dtype=torch.float16)
tensor_data_ex2.dtype

torch.float16

Other Parameters in defining a tensor

In [35]:
tensor_data_ex2 = torch.tensor([1.0,2.0,3.0], 
                               dtype=torch.float32, 
                               device = "cpu", # This tells us which device the tensor resides on. It can be on cuda, cpu etc.
                               requires_grad=False # This tells us whether we should track the gradients of the tensor or not. 
                               )
tensor_data_ex2.dtype

torch.float32

# Important Point
Two tensors can only interact together when they are on the same device. For example, if a tensor t1 is on "cpu", and tensor t2 is on "cuda", then any operation between t1 and t2 will throw an error. To do the operation, t1 and t2 must be on the same device (both on cpu or cuda)

In [44]:
pro = tensor_data_ex1 * tensor_data_ex2 #Performing a tensor operation of multiplication (elementwise)
print("datatype:",pro.dtype)
print("shape:",pro.shape)
print("dimensions:",pro.ndim)
print("device:",pro.device)


device(type='cpu')

Tensor Operations

In [47]:
# Some common operations on tensors are addition, subtraction , multiplication, division, matrix multiplication
op_tensor = torch.tensor([1,2,3,4])
print("tensor+tensor:",op_tensor+op_tensor)
print("tensor-tensor:",op_tensor-op_tensor)
print("tensor*tensor:",op_tensor*op_tensor)
print("tensor/tensor:",op_tensor/op_tensor)
print("tensor+tensor:",torch.add(op_tensor, op_tensor))
print("tensor-tensor:",torch.sub(op_tensor, op_tensor))
print("tensor*tensor:",torch.mul(op_tensor, op_tensor))
print("tensor/tensor:",torch.div(op_tensor, op_tensor))
print("tensor+tensor:",torch.add(op_tensor, 10))

tensor+tensor: tensor([2, 4, 6, 8])
tensor-tensor: tensor([0, 0, 0, 0])
tensor*tensor: tensor([ 1,  4,  9, 16])
tensor/tensor: tensor([1., 1., 1., 1.])
tensor+tensor: tensor([2, 4, 6, 8])
tensor-tensor: tensor([0, 0, 0, 0])
tensor*tensor: tensor([ 1,  4,  9, 16])
tensor/tensor: tensor([1., 1., 1., 1.])
tensor+tensor: tensor([11, 12, 13, 14])
