In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
# print("hello world")
data = pd.read_csv("train.csv")

In [3]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [4]:
data  = np.array(data)
m,n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T
y_dev = data_dev[0]
x_dev = data_dev[1:n]
x_dev = x_dev/255.0

data_train = data[1000:m].T
y_train = data_train[0]
x_train = data_train[1:n]
x_train = x_train/255.0
_,m_train = x_train.shape

In [5]:
# x_train[:,0].shape
y_train

array([1, 0, 6, ..., 0, 6, 2], dtype=int64)

In [6]:
def init_params():
    W1 = np.random.rand(10,784) - 0.5
    b1 = np.random.rand(10,1) - 0.5

    W2 = np.random.rand(10,10) - 0.5
    b2 = np.random.rand(10,1) - 0.5
    return W1,b1,W2,b2

def Relu(Z):
    return np.maximum(0,Z)  

def Softmax(Z):
    return np.exp(Z)/sum(np.exp(Z))

def forward_prop(W1,b1,W2,b2,X):
    Z1 = W1.dot(X)+b1
    A1 = Relu(Z1)

    Z2 = W2.dot(A1) + b2
    A2 = Softmax(Z2)
    return Z1,A1,Z2,A2

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max()+1))
    one_hot_Y[np.arange(Y.size),Y] =1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def deriv_relu(Z):
    return Z>0

def back_prop(Z1, A1, Z2, A2, W2, X, Y):
     one_hot_Y = one_hot(Y)
     dL_Z2 = 2 * (A2 - one_hot_Y)
     dL_W2 = 1/m * dL_Z2.dot(A1.T)
     dL_b2 = 1/m * np.sum(dL_Z2)
    
     dL_Z1 = W2.T.dot(dL_Z2) * deriv_relu(Z1)
     dL_W1 = 1/m * dL_Z1.dot(X.T)
     dL_b1 = 1/m * np.sum(dL_Z1)
     return dL_W1, dL_b1, dL_W2, dL_b2

def update_params(W1, b1, W2, b2, dL_W1, dL_b1, dL_W2, dL_b2, alpha):
    W1 = W1 - alpha * dL_W1
    b1 = b1 -  alpha * dL_b1
    W2 = W2 - alpha * dL_W2
    b2 = b2 -  alpha * dL_b2
    return W1, b1, W2, b2

In [7]:
def get_predicts(A2):
    return np.argmax(A2,0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions==Y) / Y.size

def gradient_descent(X,Y, iters, alpha):
    W1, b1, W2, b2 = init_params()
    for i in range(iters):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2,X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W2, X,Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if(i%10==0):
            print("Interation: ", i)
            print("Accuracy: ", get_accuracy(get_predicts(A2), Y))
    return W1, b1, W2, b2

In [8]:
W1, b1, W2, b2 = gradient_descent(x_train, y_train, 500, 0.1)

Interation:  0
[1 7 7 ... 5 1 7] [1 0 6 ... 0 6 2]
Accuracy:  0.15795121951219512
Interation:  10
[1 2 3 ... 0 1 2] [1 0 6 ... 0 6 2]
Accuracy:  0.2631219512195122
Interation:  20
[1 6 6 ... 0 3 2] [1 0 6 ... 0 6 2]
Accuracy:  0.3790487804878049
Interation:  30
[1 0 6 ... 0 3 2] [1 0 6 ... 0 6 2]
Accuracy:  0.4451951219512195
Interation:  40
[1 0 6 ... 0 3 2] [1 0 6 ... 0 6 2]
Accuracy:  0.5026341463414634
Interation:  50
[1 0 6 ... 0 3 2] [1 0 6 ... 0 6 2]
Accuracy:  0.5493170731707318
Interation:  60
[1 0 6 ... 0 3 2] [1 0 6 ... 0 6 2]
Accuracy:  0.5918780487804878
Interation:  70
[1 0 6 ... 0 3 2] [1 0 6 ... 0 6 2]
Accuracy:  0.6266341463414634
Interation:  80
[1 0 6 ... 0 3 2] [1 0 6 ... 0 6 2]
Accuracy:  0.6589268292682927
Interation:  90
[1 0 6 ... 0 3 2] [1 0 6 ... 0 6 2]
Accuracy:  0.686829268292683
Interation:  100
[1 0 6 ... 0 3 2] [1 0 6 ... 0 6 2]
Accuracy:  0.7110243902439024
Interation:  110
[1 0 6 ... 0 3 2] [1 0 6 ... 0 6 2]
Accuracy:  0.7199512195121951
Interation:  12

In [9]:
def make_predictions(X, W1, b1, W2, b2):
    _,_,_,A2 = forward_prop(W1, b1, W2, b2, X)
    preds = get_predicts(A2)
    return preds

In [10]:
dev_preds = make_predictions(x_dev, W1, b1, W2, b2)
get_accuracy(dev_preds, y_dev)

[9 9 7 6 9 2 1 4 8 0 7 3 3 5 1 6 4 2 1 6 8 3 8 2 7 6 1 2 3 1 4 6 2 6 3 1 3
 3 0 6 9 1 5 1 2 3 4 3 8 3 4 1 1 9 1 1 7 1 8 1 7 5 2 7 8 4 8 2 5 4 4 5 0 1
 4 6 5 3 8 6 1 6 6 2 8 8 7 7 1 8 4 6 7 3 8 3 6 6 7 3 0 9 5 4 3 0 8 6 0 8 6
 1 4 4 4 0 9 5 3 6 4 3 1 0 8 8 5 5 2 8 4 3 7 2 3 4 0 3 6 8 8 0 6 6 8 8 1 5
 6 3 1 0 9 1 0 0 2 8 7 0 9 6 6 6 2 7 8 3 0 0 1 1 6 6 8 0 5 1 8 9 7 4 3 2 9
 6 8 3 4 0 0 5 8 4 0 1 5 8 7 8 8 1 3 6 9 1 4 3 5 2 0 0 6 6 5 8 3 3 0 6 0 9
 3 2 8 2 1 1 4 0 0 5 7 5 0 9 2 5 7 6 9 6 7 3 2 2 8 2 5 3 1 6 8 2 5 5 3 7 6
 6 8 1 0 7 0 5 4 8 1 9 3 4 9 8 3 4 4 1 1 8 3 1 7 9 2 3 7 8 8 1 8 4 2 0 7 0
 6 7 7 0 7 3 1 2 4 4 7 8 4 2 1 1 3 9 0 1 1 2 6 4 2 2 9 7 6 4 2 1 5 1 1 0 8
 6 6 1 2 0 9 5 4 6 3 4 2 1 1 7 7 4 8 4 5 2 7 6 2 1 6 9 8 5 9 6 8 5 5 6 2 5
 6 5 5 4 0 6 7 1 2 3 0 0 0 7 3 8 0 9 8 4 2 4 9 9 1 7 3 9 8 8 6 8 0 1 8 5 1
 4 7 0 0 8 6 0 4 3 6 7 2 0 1 2 1 8 6 9 6 3 6 3 5 8 5 9 7 9 8 3 7 7 5 8 4 3
 4 6 3 1 5 3 4 1 1 4 6 0 7 7 3 2 2 0 0 7 9 0 4 4 8 1 1 6 7 1 5 6 2 9 5 4 5
 1 7 3 3 6 2 2 3 7 6 7 6 

0.862