In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
# print("hello world")
data = pd.read_csv("train.csv")

In [3]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [4]:
data  = np.array(data)
m,n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T
y_dev = data_dev[0]
x_dev = data_dev[1:n]
x_dev = x_dev/255.0

data_train = data[1000:m].T
y_train = data_train[0]
x_train = data_train[1:n]
x_train = x_train/255.0
_,m_train = x_train.shape

In [5]:
# x_train[:,0].shape
y_train

array([4, 8, 0, ..., 8, 6, 5], dtype=int64)

In [6]:
def init_params():
    W1 = np.random.rand(10,784) - 0.5
    b1 = np.random.rand(10,1) - 0.5

    W2 = np.random.rand(10,10) - 0.5
    b2 = np.random.rand(10,1) - 0.5
    return W1,b1,W2,b2

def Relu(Z):
    return np.maximum(0,Z)

def Softmax(Z):
    return np.exp(Z)/sum(np.exp(Z))

def forward_prop(W1,b1,W2,b2,X):
    Z1 = W1.dot(X)+b1
    A1 = Relu(Z1)

    Z2 = W2.dot(A1) + b2
    A2 = Softmax(Z2)
    return Z1,A1,Z2,A2

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max()+1))
    one_hot_Y[np.arange(Y.size),Y] =1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def deriv_relu(Z):
    return Z>0

def back_prop(Z1, A1, Z2, A2, W2, X, Y):
     one_hot_Y = one_hot(Y)
     dZ2 = A2 - one_hot_Y
     dW2 = 1/m * dZ2.dot(A1.T)
     db2 = 1/m * np.sum(dZ2)
     dZ1 = W2.T.dot(dZ2) * deriv_relu(Z1)
     dW1 = 1/m * dZ1.dot(X.T)
     db1 = 1/m * np.sum(dZ1)
     return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 -  alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 -  alpha * db2
    return W1, b1, W2, b2

In [7]:
def get_predicts(A2):
    return np.argmax(A2,0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions==Y) / Y.size

def gradient_descent(X,Y, iters, alpha):
    W1, b1, W2, b2 = init_params()
    for i in range(iters):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2,X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W2, X,Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if(i%10==0):
            print("Interation: ", i)
            print("Accuracy: ", get_accuracy(get_predicts(A2), Y))
    return W1, b1, W2, b2

In [8]:
W1, b1, W2, b2 = gradient_descent(x_train, y_train, 500, 0.1)

Interation:  0
[7 0 0 ... 0 7 0] [4 8 0 ... 8 6 5]
Accuracy:  0.09546341463414634


Interation:  10
[3 9 0 ... 0 7 0] [4 8 0 ... 8 6 5]
Accuracy:  0.1653658536585366
Interation:  20
[4 9 0 ... 0 7 0] [4 8 0 ... 8 6 5]
Accuracy:  0.2651219512195122
Interation:  30
[4 9 0 ... 0 7 5] [4 8 0 ... 8 6 5]
Accuracy:  0.36441463414634145
Interation:  40
[4 9 0 ... 0 7 5] [4 8 0 ... 8 6 5]
Accuracy:  0.4472926829268293
Interation:  50
[4 9 0 ... 0 7 5] [4 8 0 ... 8 6 5]
Accuracy:  0.5127073170731707
Interation:  60
[4 9 0 ... 0 7 5] [4 8 0 ... 8 6 5]
Accuracy:  0.5584634146341464
Interation:  70
[4 9 0 ... 0 7 5] [4 8 0 ... 8 6 5]
Accuracy:  0.5937560975609756
Interation:  80
[4 9 0 ... 0 4 5] [4 8 0 ... 8 6 5]
Accuracy:  0.6218780487804878
Interation:  90
[4 9 0 ... 0 4 5] [4 8 0 ... 8 6 5]
Accuracy:  0.6461951219512195
Interation:  100
[4 9 0 ... 0 4 5] [4 8 0 ... 8 6 5]
Accuracy:  0.6659268292682927
Interation:  110
[4 9 0 ... 0 4 5] [4 8 0 ... 8 6 5]
Accuracy:  0.6843414634146342
Interation:  120
[4 9 0 ... 0 4 5] [4 8 0 ... 8 6 5]
Accuracy:  0.7004146341463414
Interation: 

In [9]:
def make_predictions(X, W1, b1, W2, b2):
    _,_,_,A2 = forward_prop(W1, b1, W2, b2, X)
    preds = get_predicts(A2)
    return preds

In [10]:
dev_preds = make_predictions(x_dev, W1, b1, W2, b2)
get_accuracy(dev_preds, y_dev)

[4 6 3 4 5 3 3 1 1 9 0 0 7 9 4 4 1 1 7 0 9 1 8 2 3 3 0 5 8 5 0 2 6 6 4 9 9
 3 1 2 6 5 1 2 3 1 1 6 3 2 5 3 7 8 9 4 6 7 1 9 8 5 1 7 1 7 1 6 8 6 9 4 6 8
 3 7 1 6 8 1 4 1 1 9 8 2 9 3 9 0 4 0 8 5 0 6 1 8 2 0 3 3 1 8 5 1 2 9 1 5 3
 2 1 9 0 7 4 1 7 7 9 3 6 2 4 3 0 4 2 9 2 3 3 3 3 9 1 5 4 0 6 2 8 9 4 6 0 7
 7 0 6 7 3 1 6 8 6 5 2 3 9 9 0 4 7 6 3 0 4 8 9 8 5 4 5 7 1 3 8 7 2 3 3 2 5
 4 5 4 1 2 8 4 4 8 9 7 9 5 2 5 7 9 5 4 7 4 4 1 0 7 2 8 4 1 7 0 1 1 7 1 0 8
 6 8 3 9 7 5 7 7 6 4 2 1 0 9 6 9 6 2 1 1 5 9 8 9 7 7 0 9 5 7 9 2 8 2 1 5 4
 8 8 4 0 9 2 9 2 6 1 3 8 3 8 1 8 9 2 4 7 6 9 9 5 1 9 4 5 1 5 7 0 3 0 7 8 8
 8 5 5 9 2 0 0 1 3 1 4 1 6 1 0 9 8 9 0 8 8 2 7 1 3 8 8 4 1 6 5 1 3 8 4 3 4
 3 8 6 0 1 3 3 7 7 4 1 2 2 4 6 8 6 1 5 4 1 3 8 2 6 9 1 8 1 6 1 2 5 7 1 5 8
 6 9 4 0 0 0 9 5 3 5 4 8 7 9 1 4 6 0 4 9 8 1 9 3 2 5 8 5 6 8 4 4 6 3 3 3 0
 6 2 1 7 7 5 2 3 0 7 2 8 5 0 8 7 3 1 9 3 8 6 5 7 1 7 9 3 0 9 7 4 1 1 8 2 9
 4 6 4 0 4 1 0 3 5 4 1 9 5 6 9 5 1 3 4 0 0 2 2 6 9 5 5 1 8 6 1 5 3 5 7 1 3
 8 1 1 3 3 5 9 4 6 5 0 1 

0.86